const catchAsyncError = require("../middleware/catchAsyncError");

exports.login = catchAsyncError(async (req, res, next) => {
    try {
        next(error);
    }
    finally {
    }
    const register = catchAsyncError(async (req, res, next) => {
    });
});
